spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mms
    username: admin
    password: adminmms
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

security:
  jwt:
    secret: Vc0AdKyBIffZ5ErS4yvib99zRZkdR5eMuxzHVDLUBNk=
    expiration: 86400000 # 24 hours in milliseconds

storage:
  type: minio  # or 's3'
  minio:
    endpoint: http://localhost:9000
    accessKey: admin
    secretKey: adminmms
    bucket: mms-media
  s3:
    region: your_aws_region
    accessKey: your_aws_access_key
    secretKey: your_aws_secret_key
    bucket: mms-media

server:
  port: 8080
  servlet:
    context-path: /api
